AI:
  keywords:
    - agents
    - inference
    - model
    - GPU
    - open-source AI
    - compute

RWA:
  keywords:
    - tokenization
    - SPV
    - transfer agent
    - private credit
    - stablecoin
    - private equity
    - Sacra
    - pre-IPO

DeFi:
  keywords:
    - lending
    - liquidity
    - yield
    - AMM
    - veTokenomics

Portfolio:
  keywords:
    - Venice
    - Dolphin
    - POD
    - VVV
    - DIEM
    - Convex (CVX)
    - Curve (CRV)
    - FXN
    - AERO
    
Personal:
 keywords:
    - personal development
    - spiritual health
    - consciousness
    - holistic lifestyle
    - healthy eating

Macro:
  keywords:
    - rates
    - treasury
    - inflation
    - regulation